version: '3.7'

services:
  main:
    container_name: task-management
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8080:8080
    command: yarn start:dev
    environment:
      SERVER_PORT: 8080
      DB_TYPE: postgres
      DB_HOSTNAME: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_PORT: 5433
      DB_SYNCHRONIZE: 'true'
      DB_DATABASE_NAME: task_management
      JWT_SECRET: top51
      JWT_EXPIRES: 3600
    networks:
      - service
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres:12
    networks:
      - service
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: task_management
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
networks:
  service:
volumes:
  pgdata:
